name: gestor_fiwi
description: "Gestor de dispositivos Wi-Fi locales y notificaciones."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^5.0.0
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
